Refer to files at current default branch
knausj85/knausj_talon pull request #1019
Opened 2022-11-05 16:10 UTC by simonnagl

This changes Links in comments and docs to refer to the new default branch.

The links to master refer to outdated versions (currently 90 commits behind)

2022-11-05 16:57 UTC, rntz requested changes
Good catch! However, some of these replacements are over-eager and have changed links to repositories other than knausj. Fix those and we can merge it.

2022-11-05 16:57 UTC, rntz commented on apps/jetbrains/jetbrains.py
> +# Courtesy of https://github.com/anonfunc/talon-user/blob/main/apps/jetbrains.py
This seems like a mistake; this isn't a knausj link, and the updated version 404s.

```suggestion
# Courtesy of https://github.com/anonfunc/talon-user/blob/master/apps/jetbrains.py
```

2022-11-05 16:57 UTC, rntz commented on core/text/text_and_dictation.py
> +# Descended from https://github.com/dwiel/talon_community/blob/main/misc/dictation.py
Likewise, a mistake.
```suggestion
# Descended from https://github.com/dwiel/talon_community/blob/master/misc/dictation.py
```

2022-11-05 16:58 UTC, rntz approved these changes
Huh, looks like I can fix them myself.

2022-11-05 16:58 UTC, merged

2022-11-06 00:33 UTC, simonnagl commented
Thanks for the thorough review and fixes. I accepted edits for maintainers on this merge request.