Search tab by title for firefox
knausj85/knausj_talon pull request #343
Opened 2021-02-01 11:31 UTC by timo

2021-02-01 13:44 UTC, rntz commented
This looks very useful! Do any other browsers have this feature? As far as I can tell chrome does not have it yet except on ChromeOS, but might soon: https://www.howtogeek.com/704212/how-to-search-open-tabs-on-google-chrome/.

1. It would be nice if the `<user.text>` could be made optional, so "tab search" on its own just brought up the tab search. That would require not hitting the `down` key afterwards, though, since that just selects the first match, eg add the following:

   ```
   tab search:
     browser.focus_address()
     insert("% ")
   ```

2. In fact, I'm not sure whether hitting the down key is a good idea at all here, since it means you can't add further text to the search without hitting up. (Also if there are no matches it ends up selecting a search engine, which is a bit weird although though not really a problem.) I guess it makes it easy to go to the first match, though, which is handy.

What do you think?

2021-02-01 13:45 UTC, knausj85 commented on apps/firefox/firefox.win.talon
> +tab search <user.text>:
for Firefox-specific commands, I'd recommend creating a new firefox.talon file that matches on
`app: firefox`
so we don't have to maintain the commands in multiple places

2021-02-01 13:46 UTC, knausj85 commented on apps/firefox/firefox.win.talon
> +	"% {text}"
this is pretty nitpicky, but for multiline commands I prefer to use explicit `insert` calls

2021-02-02 09:14 UTC, fidgetingbits requested changes
on my branch I actually implemented a tab search action in tabs.py and then implemented this that way:

```
action(user.tab_search):
	browser.focus_address()
    key(%)
```

I hadn't got around to merging into main line yet but I feel like it's probably better to go that route, since we already have tab commands?

I use this command a lot though I agree it's useful

2021-02-19 13:48 UTC, rntz commented
Bumping this, because it looks really useful and seems to have stalled — timo, are you planning on working on this PR? If not I can try and finish it up this weekend.

2021-02-21 20:17 UTC, closed without merging