Tara add talon resource websites
knausj85/knausj_talon pull request #806
Opened 2022-03-20 19:29 UTC by tararoys

To lower the activation energy for people to be able to get to the websites where you can find help, I added 

    "talon website":"http://talonvoice.com",
    "talon slack":"http://talonvoice.slack.com/messages/help",
    "talon wiki":"https://talon.wiki/",
    "talon practice":"https://chaosparrot.github.io/talon_practice/",
    "talon repository search": "https://search.talonvoice.com/search/",
    
    As defaults to website.csv, so that the command 
    
    *open talon website*  launches the talon website
    *open talon slack* launches the talon slack  and puts you in the help channel by default
    *open talon wiki* launches the talon wiki
    *open talon practice* goes to chaosparrot's talon practice website.

2022-03-22 19:47 UTC, pokey requested changes
Great call to add these in.  Left a bunch of minor comments

2022-03-22 19:47 UTC, pokey commented on modes/dictation_mode.talon
> +experiment: anchor-file
this looks accidental too

2022-03-22 19:47 UTC, pokey commented on modes/modes.talon
> +  mode.enable("command")
and this

2022-03-22 19:47 UTC, pokey commented on code/websites_and_search_engines.py
> +    "talon slack":"http://talonvoice.slack.com/messages/help",
let's switch these to `https`
```suggestion
    "talon website":"https://talonvoice.com",
    "talon slack":"https://talonvoice.slack.com/messages/help",
```

2022-03-22 19:47 UTC, pokey commented on code/websites_and_search_engines.py
> +    "talon repository search": "https://search.talonvoice.com/search/",
maybe shorten a bit?
```suggestion
    "talon repo search": "https://search.talonvoice.com/search/",
```

2022-03-22 19:47 UTC, pokey commented on code/websites_and_search_engines.py
> +    "talon website":"http://talonvoice.com",
Technically all of these are websites.  Maybe
```suggestion
    "talon home page":"http://talonvoice.com",
```

2022-03-23 02:07 UTC, tararoys commented
Yeah, i accidenally included a bunch of minor additons to the knausj.  Unfortunately I need someone to walk me through how to exclude the unintended changes like the weird mixed mode stuff and include only the intended chnages, like the websites I want included as defaults.  Can someone walk me through it?

2022-03-26 13:56 UTC, merged

2022-03-28 15:34 UTC, pokey commented on code/websites_and_search_engines.py
> +    "talon slack":"http://talonvoice.slack.com/messages/help",
@rntz / @tararoys looks like maybe you missed this comment?

2022-03-28 15:35 UTC, pokey commented on code/websites_and_search_engines.py
> +    "talon website":"http://talonvoice.com",
@rntz / @tararoys and one more?