Add support for relative home paths
knausj85/knausj_talon pull request #963
Opened 2022-08-28 09:15 UTC by SandeepJoel

The change will allow us to have the entries like below in the settings/system_path.csv. 
`~/Downloads/screenshots, screenshots`

This can be useful if we're using this same file for multiple machines having different usernames using dotFiles approach.

2022-08-28 12:07 UTC, rntz requested changes

2022-08-28 12:07 UTC, rntz commented on apps/generic_terminal/generic_terminal.talon
> +go <user.system_path>: insert("cd {system_path} \n")
This is a bad idea, as it means any path that contains spaces (or other characters with special meaning to the shell) will not work without escaping. Instead, I suggest making a capture `<user.system_path>` which calls `os.expanduser` on the path.

2022-10-30 14:20 UTC, auscompgeek commented
Workaround: Use environment variables such as `$HOME` or `%USERPROFILE%` in the CSV.

2022-11-19 14:42 UTC, rntz commented
this would partially address #1036

2022-12-04 01:52 UTC, splondike commented
It sounds like we'd need some changes to the current implementation to want to merge this in. Since the PR hasn't moved in a few months, wouldn't fully address #1036, and is so simple I'm just going to close this out.

2022-12-04 01:52 UTC, closed without merging